services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8080:80"
      - "8443:443"
    environment:
      - DEBUG=1
      - PERSISTENCE=0
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - SKIP_INFRA_DOWNLOADS=1
      - TMPDIR=/tmp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
